using Revise
using Makie
using CairoMakie
using Plots
using LinearAlgebra
using Random
using ArgParse
using Flux
using MLDatasets
using CSV
using DataFrames
using Dates
using Distributions
using Images
using Test
using Serialization
using Logging
using LoggingExtras
global_logger(ConsoleLogger(stderr, Logging.Info))
#global_logger(ConsoleLogger(stdout))
